CREATE TABLE Puntos (
  valor INT NOT NULL 
    CHECK (
      valor > 0
    )
);

CREATE TABLE Miembro (
    ID_Miembro NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Tipo_Miembro VARCHAR2(10) NOT NULL
      CHECK (
        Tipo_Miembro IN ('PROFESOR', 'ESTUDIANTE', 'EMPLEADO')
      ),
    Genero CHAR(1) NOT NULL
      CHECK(
        Genero IN ('F', 'M')
      ),
    Correo VARCHAR2(255) NOT NULL
      CHECK(
        Correo LIKE '%_@_%_.__%'
      ),
    Puntos_Acumulados INT,
    PRIMARY KEY (ID_Miembro)
  
);

CREATE TABLE Edificio (
  Nombre VARCHAR2(255) NOT NULL,
  
  PRIMARY KEY (Nombre)
);

CREATE TABLE Piso (
  ID_Piso NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  Nombre_Edificio VARCHAR2(255) NOT NULL,

  PRIMARY KEY (ID_Piso),
  FOREIGN KEY (Nombre_Edificio) REFERENCES Edificio(Nombre)
    ON DELETE SET NULL
);

CREATE TABLE Cafeteria (
  Nombre VARCHAR2(255) NOT NULL,
  ID_Piso NUMBER NOT NULL,
  Nombre_Edificio VARCHAR2(255) NOT NULL,

  PRIMARY KEY (Nombre),
  FOREIGN KEY (ID_Piso) REFERENCES Piso(ID_Piso)
    ON DELETE SET NULL,
  FOREIGN KEY (Nombre_Edificio) REFERENCES Edificio(Nombre)
    ON DELETE SET NULL
);

CREATE TABLE Producto (
  ID_Producto NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  Nombre VARCHAR2(255) NOT NULL,
  Precio NUMBER NOT NULL
    CHECK (
      Precio >= 0
    ),

  PRIMARY KEY (ID_Producto)
);

CREATE TABLE Colaborador (
  ID_Colaborador NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  Nombre VARCHAR2(255) NOT NULL,
  Tipo_Contrato VARCHAR2(50) NOT NULL
    CHECK (
      Tipo_Contrato IN ( 'TEMPORAL', 'PLANTA' )
    ),
    Nombre_Cafeteria VARCHAR2(255) NOT NULL,

  PRIMARY KEY (ID_Colaborador),
  FOREIGN KEY (Nombre_Cafeteria) REFERENCES Cafeteria(Nombre)
    ON DELETE SET NULL
);

CREATE TABLE InventarioCafeteria (
  Nombre_Cafeteria VARCHAR2(255) NOT NULL,
  ID_Producto NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  Existencias INT NOT NULL
    CHECK (
      Existencias >= 0
    ),

  PRIMARY KEY (Nombre_Cafeteria, ID_Producto),
  FOREIGN KEY (Nombre_Cafeteria) REFERENCES Cafeteria(Nombre)
    ON DELETE SET NULL,
  FOREIGN KEY (ID_Producto) REFERENCES Producto(ID_Producto)
    ON DELETE SET NULL
);

CREATE TABLE Compra (
  ID_Compra NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ID_Miembro NUMBER NOT NULL,
  ID_Colaborador NUMBER NOT NULL,
  Nombre_Cafeteria VARCHAR2(255) NOT NULL,

  Fecha DATE NOT NULL,
  Total_Compra NUMBER NOT NULL
    CHECK (
      Total_Compra >= 0
    ),

  PRIMARY KEY (ID_Compra),
  FOREIGN KEY (ID_Miembro) REFERENCES Miembro(ID_Miembro)
    ON DELETE SET NULL,
  FOREIGN KEY (Nombre_Cafeteria) REFERENCES Cafeteria(Nombre)
    ON DELETE SET NULL,
  FOREIGN KEY (ID_Colaborador) REFERENCES Colaborador(ID_Colaborador)
    ON DELETE SET NULL
); 

CREATE TABLE CompraxProducto (
  ID_Compra NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ID_Producto NUMBER NOT NULL,
  Cantidad INT NOT NULL
    CHECK (
      Cantidad > 0
    ),

  PRIMARY KEY (ID_Compra, ID_Producto),
  FOREIGN KEY (ID_Compra) REFERENCES Compra(ID_Compra)
    ON DELETE SET NULL,
  FOREIGN KEY (ID_Producto) REFERENCES Producto(ID_Producto)
    ON DELETE SET NULL
);

CREATE TABLE TxPuntos (
  ID_TxPuntos NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ID_Compra NUMBER,

  Fecha DATE NOT NULL,
  Total_Puntos NUMBER NOT NULL
    CHECK (
      Total_Puntos != 0
    ),
  Tipo VARCHAR2(10) NOT NULL
    CHECK (
      Tipo IN ('CANJE', 'COMPRA', 'ACUMULAR')
    ),

  PRIMARY KEY (ID_TxPuntos),
  FOREIGN KEY (ID_Compra) REFERENCES Compra(ID_Compra)
    ON DELETE SET NULL
);

CREATE TABLE ImpuestoXCompra (
  ID_Impuesto NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ID_Compra NUMBER NOT NULL,

  Tipo_Impuesto VARCHAR2(20) NOT NULL
    CHECK (
      Tipo_Impuesto IN ('IVA', 'ISR', 'ICA')
    ),
  Total_Impuesto NUMBER NOT NULL
    CHECK (
      Total_Impuesto >= 0
    ),
  Porcentaje NUMBER NOT NULL
    CHECK (
      Porcentaje >= 0 AND
      Porcentaje <= 100
    ),

  PRIMARY KEY (ID_Impuesto),
  FOREIGN KEY (ID_Compra) REFERENCES Compra(ID_Compra)
    ON DELETE SET NULL
);

CREATE TABLE Pago (
  ID_Pago NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ID_Compra NUMBER NOT NULL,
  Monto_total NUMBER NOT NULL
    CHECK (
      Monto_total >= 0
    ),
  Metodo_Pago VARCHAR2(20) NOT NULL
    CHECK (
      Metodo_Pago IN ('CREDITO', 'DEBITO', 'EFECTIVO', 'PUNTOS')
    ),
  Numero_Tarjeta VARCHAR2(16),

  PRIMARY KEY (ID_Pago),
  FOREIGN KEY (ID_Compra) REFERENCES Compra(ID_Compra)
    ON DELETE SET NULL
);